#eureka:
#  client:
#    register-with-eureka: false #自己是否注册到erueka中
#    fetch-registry: false #是否从其他eruekaserver中拉取注册表，单节点不存在其他eruekaservice
#    serviceUrl:
#      defaultZone: http://root:root@localhost:7900/eureka/  #与ES交互的地址 查询注册都依赖此地址 默认为http://localhost:8761/eureka 多个地址使用","分割
spring:
  application:
    name: erueka
  security:
    user:
      name: root
      password: root
logging:
  level:
    root: debug
---
spring:
  profiles: 7901
server:
  port: 7901
eureka:
  instance:
    hostname: localhost
  client:
    #设置服务注册中心的URL
    service-url:
      defaultZone: http://root:root@localhost:7902/eureka/
---
spring:
  profiles: 7902
server:
  port: 7902
eureka:
  instance:
    hostname: localhost
  client:
    #设置服务注册中心的URL
    service-url:
      defaultZone: http://root:root@localhost:7901/eureka/
